<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Film extends \Entity\Film implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function getRating()
    {
        $this->__load();
        return parent::getRating();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getImg()
    {
        $this->__load();
        return parent::getImg();
    }

    public function getDesc()
    {
        $this->__load();
        return parent::getDesc();
    }

    public function getPlaying()
    {
        $this->__load();
        return parent::getPlaying();
    }

    public function getSoon()
    {
        $this->__load();
        return parent::getSoon();
    }

    public function getTrailer()
    {
        $this->__load();
        return parent::getTrailer();
    }

    public function getStart()
    {
        $this->__load();
        return parent::getStart();
    }

    public function getEnd()
    {
        $this->__load();
        return parent::getEnd();
    }

    public function getStat()
    {
        $this->__load();
        return parent::getStat();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id_film', 'title', 'rating', 'synopsis', 'start', 'end', 'image', 'trailer', 'havings');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}